// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {datalake} from '../models';

export function GetHistory():Promise<Array<model.SyncLog>>;

export function IngestFile(arg1:string,arg2:string,arg3:string):Promise<datalake.Stats>;

export function RetryConnectDB():Promise<boolean>;
