// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function IngestFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['IngestFile'](arg1, arg2, arg3);
}

export function RetryConnectDB() {
  return window['go']['main']['App']['RetryConnectDB']();
}
